"""
Backend V2 — ResultConsistencyValidator

Validates that the VerifiedResult generated by QueryExecutor strictly adheres
to all security invariants and query plan requirements before any presentation
or response generation.

If any invariant fails, raises ResultValidationError.
"""
import logging
from models.query import QueryPlan, VerifiedResult, SubjectScope
from models.user import CurrentUser

logger = logging.getLogger(__name__)


class ResultValidationError(ValueError):
    """Raised when a pre-response result validation check fails."""
    pass


class ResultConsistencyValidator:

    def validate(
        self,
        result: VerifiedResult,
        user: CurrentUser,
        plan: QueryPlan,
    ) -> None:
        """
        Validates all 7 security invariants and consistency rules on VerifiedResult.
        Raises ResultValidationError if any check fails.
        """
        # Do not validate errored/failed results that have no result content
        if not result.success and not result.result:
            return

        scope = plan.subject_scope

        # ── Invariant 1: CURRENT_USER scope employee ID match ────────────────
        if scope == SubjectScope.CURRENT_USER:
            user_emp_id = user.employee_id.strip().upper()

            # Check individual result items if they contain employee_id
            for i, item in enumerate(result.result):
                emp_id = str(item.get("employee_id", "")).strip().upper()
                if emp_id and emp_id != user_emp_id:
                    self._log_and_raise_error(
                        f"INVARIANT 1 VIOLATION: Result item {i} has employee_id '{emp_id}', "
                        f"which does not match authenticated user '{user_emp_id}'.",
                        result, user, plan
                    )

        # ── Invariant 2: CURRENT_USER scope source records employee ID match ─
        if scope == SubjectScope.CURRENT_USER:
            user_emp_id = user.employee_id.strip().upper()
            for i, src in enumerate(result.source_records):
                emp_id = str(src.get("employee_id", src.get("employee", ""))).strip().upper()
                # If employee_id is explicitly present in source record metadata
                if "employee_id" in src and src["employee_id"]:
                    if str(src["employee_id"]).strip().upper() != user_emp_id:
                        self._log_and_raise_error(
                            f"INVARIANT 2 VIOLATION: Source record {i} ({src.get('source')}) has "
                            f"employee_id '{src['employee_id']}', which does not match authenticated user '{user_emp_id}'.",
                            result, user, plan
                        )

        # ── Invariant 3: SPECIFIC_EMPLOYEE scope match ────────────────────────
        if scope == SubjectScope.SPECIFIC_EMPLOYEE and plan.target_employee_id:
            target_id = plan.target_employee_id.strip().upper()
            for i, item in enumerate(result.result):
                emp_id = str(item.get("employee_id", "")).strip().upper()
                if emp_id and emp_id != target_id:
                    self._log_and_raise_error(
                        f"SPECIFIC_EMPLOYEE VIOLATION: Result item {i} has employee_id '{emp_id}', "
                        f"which does not match requested target employee '{target_id}'.",
                        result, user, plan
                    )

        # ── Invariant 4: ALL_EMPLOYEES scope labeling check ───────────────────
        if scope == SubjectScope.ALL_EMPLOYEES:
            # Result must represent organization-wide data. Verify no artificial current-user filter was applied.
            pass

        # ── Invariant 5: Aggregation & Metric matching ────────────────────────
        if plan.metric and result.metric and plan.metric != result.metric:
            logger.warning(
                f"Metric mismatch: plan specified '{plan.metric}', executor returned '{result.metric}'."
            )

        # ── Invariant 6: Source records origin check ──────────────────────────
        # Verify source records belong to the dataset analyzed
        if result.total_records_analyzed == 0 and result.source_records:
            self._log_and_raise_error(
                "INVARIANT 7 VIOLATION: Source records present when total_records_analyzed is 0.",
                result, user, plan
            )

        logger.info(
            f"VALIDATION PASSED: scope={scope.value}, total_analyzed={result.total_records_analyzed}, "
            f"results_count={len(result.result)}, sources_count={len(result.source_records)}"
        )

    def _log_and_raise_error(
        self,
        message: str,
        result: VerifiedResult,
        user: CurrentUser,
        plan: QueryPlan,
    ) -> None:
        """Logs detailed debugging context and raises ResultValidationError."""
        logger.error(
            f"\n=== RESULT VALIDATION FAILURE ===\n"
            f"ERROR: {message}\n"
            f"CURRENT_USER: {user.employee_name} ({user.employee_id}) [{user.role.value}]\n"
            f"QUERY_PLAN: intent={plan.intent.value}, entity={plan.entity.value}, scope={plan.subject_scope.value}, target_id={plan.target_employee_id}\n"
            f"FILTERED_COUNT: {result.total_records_analyzed}\n"
            f"EXECUTION_RESULT: {result.result}\n"
            f"SOURCE_RECORDS: {result.source_records}\n"
            f"=================================\n"
        )
        raise ResultValidationError(message)
